server:
  port: 9010

spring:
  application:
    name: RBAC
  # datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/rbac
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: C8aJEVCCvSA1VFi8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis config
  redis:
    host: localhost
    port: 6379
    password: C8aJEVCCvSA1VFi8
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

# swagger config
swagger:
  title: RBAC
  description: API documentation for RBAC.
  version: 1.0.0

# base-packages
packages:
  controller: com.imyuanxiao.rbac.controller


logging:
  level:
    root: info
    com.imyuanxiao.rbac: debug

